name: Add ToDo Item to ToDo project

on:
  issues:
    types:
      - opened

env:
  PROJECRT_NUMBER: 3
  PROJECRT_OWNER: hidetzu

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.0.5
        with:
          # to the issue
          #project-url: https://github.com/users/hidetzu/projects/3
          project-url: https://github.com/users/${{ env.PROJECRT_OWNER }}/projects/${{ env.PROJECRT_NUMBER }}
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          labeled: "◻️Todo"
